---
title: "11-kallisto"
author: "Steven Roberts"
date: "`r format(Sys.time(), '%d %B, %Y')`"  
analyses: 
  github_document:
    toc: true
    toc_depth: 3
    number_sections: true
    html_preview: true
  html_document:
    theme: readable
    highlight: zenburn
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
    code_download: true
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
library(knitr)
library(tidyverse)
library(kableExtra)
library(DT)
library(Biostrings)
library(tm)
library(pheatmap)
library(DESeq2)
knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = FALSE,         # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 6,       # Set plot width in inches
  fig.height = 4,      # Set plot height in inches
  fig.align = "center", # Align plots to the center
  comment = ""         # Prevents appending '##' to beginning of lines in code analyses
)
```

# Reads 

```{r, engine='bash', eval=TRUE}
ls /home/shared/8TB_HDD_02/graceac9/data/pycno2021/*
```

# indexing



```{r, engine='bash', eval=TRUE}
head /home/shared/8TB_HDD_02/graceac9/GitHub/project-pycno-sizeclass-2022/data/augustus.hints.codingseq
```


```{r, engine='bash'}
/home/shared/kallisto/kallisto index \
-i ../analyses/11-kallisto/Ph.codingseq.index \
/home/shared/8TB_HDD_02/graceac9/GitHub/project-pycno-sizeclass-2022/data/augustus.hints.codingseq
```



```{r, engine='bash'}
find /home/shared/8TB_HDD_02/graceac9/data/pycno2021/*_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
| xargs -I{} basename -s _R1_001.fastq.gz.fastp-trim.20220810.fq.gz {} \
| xargs -I{} sh -c '/home/shared/kallisto/kallisto quant \
-i ../analyses/11-kallisto/Ph.codingseq.index \
-o ../analyses/11-kallisto/kallisto_01/{} \
-t 10 \
--fr-stranded /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
--rf-stranded /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R2_001.fastq.gz.fastp-trim.20220810.fq.gz \
> ../analyses/11-kallisto/{}_kall01.stdout 2> ../analyses/11-kallisto/{}_kall01.stderr'
```



```{r, engine='bash'}
eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate
which multiqc


multiqc ../analyses/11-kallisto/kallisto_01 \
-o ../analyses/11-kallisto/kallisto_01
```

```{r, engine='bash'}
head ../data/Phel_transcriptome.fasta
```

```{r, engine='bash'}
/home/shared/kallisto/kallisto index \
-i ../analyses/11-kallisto/Phel_transcriptome.uia.index \
../data/Phel_transcriptome.fasta
```


```{r, engine='bash'}
find /home/shared/8TB_HDD_02/graceac9/data/pycno2021/*_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
| xargs -I{} basename -s _R1_001.fastq.gz.fastp-trim.20220810.fq.gz {} \
| xargs -I{} sh -c '/home/shared/kallisto/kallisto quant \
-i ../analyses/11-kallisto/Phel_transcriptome.uia.index \
-o ../analyses/11-kallisto/kallisto_02/{} \
-t 36 \
--fr-stranded /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R1_001.fastq.gz.fastp-trim.20220810.fq.gz \
--rf-stranded /home/shared/8TB_HDD_02/graceac9/data/pycno2021/{}_R2_001.fastq.gz.fastp-trim.20220810.fq.gz \
> ../analyses/11-kallisto/kallisto_02/{}_kall02.stdout 2> ../analyses/11-kallisto/kallisto_02/{}_kall02.stderr'
```


```{r, engine='bash'}
eval "$(/opt/anaconda/anaconda3/bin/conda shell.bash hook)"
conda activate
which multiqc


multiqc ../analyses/11-kallisto/kallisto_02 \
-o ../analyses/11-kallisto/kallisto_02
```