---
title: "24-2021-2022-enrichment"
output: html_document
date: "2024-10-15"
---
Rmd to get enriched processes from 2021 work using DAVID and revigo. 
Packages needed:
```{r}
library(dplyr)
library(tidyverse)
```


Get uniprot accession IDs into a .txt from the genome blast output: 
Read in blast output:
```{r}
blast <- read.table("../analyses/16-blast-annotation/blast_out_sep_genes.tab", )
head(blast)
```
Rename columns: 
```{r}
colnames(blast) <- c("gene_id", "V2", "uniprot_accession", "gene_name", "V5", "V6", "V7", "V8", "V9", "V10", "V11", "V12", "V13", "V14")
head(blast)
```

```{r}
blastuniprot <- select(blast, uniprot_accession)
head(blastuniprot)
```

write out as a txt file: 
```{r}
#write.csv(blastuniprot, "../analyses/24-2021-2022-enrichment/blastuniprot.csv")
```
write out 2024-10-15. comment out code. 



# 2021 DEG list 
```{r}
deg21 <- read.delim("../analyses/23-annotating-deg-lists/DEGlist_2021_exposedVcontrol_annotated.tab")
head(deg21)
```

subset the uniprot_accession column:
```{r}
deg21uniprot <- select(deg21, uniprot_accession)
head(deg21uniprot)
```

write out: 
```{r}
#write.csv(deg21uniprot, "../analyses/24-2021-2022-enrichment/2021_deg_uniprot_accessions.csv")
```
write out 2024-10-15. comment out code. 





